name: Check Module

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: string
      pipeline_id:
        description: 'Corefinity Pipeline ID'
        required: true
        type: string
      # corefinity_api_key:
      #   description: 'Corefinity API Key'
      #   required: true
      #   type: string
      # mdoq_api_key:
      #   description: 'MDOQ API Key'
      #   required: true
      #   type: string
    secrets:
      mdoq_api_key:
        required: true
      corefinity_api_key:
        required: true
      github_token:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Foo
        run: |
          echo '${{ toJSON(secrets) }}'
          echo "mdoq_api_key: "
          echo ${{ secrets.mdoq_api_key }}
          echo "corefinity_api_key: "
          echo ${{ secrets.corefinity_api_key }}
          echo "BLAH: "
          echo ${{ secrets.BLAH }}
          echo "working"
          ls -lath