name: Check Module

on:
  workflow_dispatch:
  workflow_call:

permissions:
  contents: read

jobs:
  deply:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Foo
        run: |
          echo "working"
          ls -lath