name: Check Module

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      tag:
        description: 'Tag to deploy'
        required: true
        type: string
      pipeline_id:
        description: 'Corefinity Pipeline ID'
        required: true
        type: string
    secrets:
      mdoq_api_key:
        required: true
      corefinity_api_key:
        required: true

permissions:
  contents: read

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - name: Foo
        run: |
          echo '${{ toJSON(secrets) }}'
          ls -lath